### ISSUE TITLE
FirebasePlugin.java:509 java.lang.IllegalStateException: Must Initialize Fabric before using singleton()

### ISSUE THREAD

**Issue by guylando** [arnesson/cordova-plugin-firebase#1007]
FirebasePlugin.java:509 version 2.0.5 throws error on android and crashes (might be related to installing https://github.com/chroa/twitter-connect-plugin plugin which also uses fabric):

02-18 20:32:01.367  3739  3739 E AndroidRuntime: java.lang.IllegalStateException: Must Initialize Fabric before using singleton()
02-18 20:32:01.367  3739  3739 E AndroidRuntime: 	at io.fabric.sdk.android.Fabric.singleton(Fabric.java:275)
02-18 20:32:01.367  3739  3739 E AndroidRuntime: 	at io.fabric.sdk.android.Fabric.getKit(Fabric.java:525)
02-18 20:32:01.367  3739  3739 E AndroidRuntime: 	at com.crashlytics.android.Crashlytics.getInstance(Crashlytics.java:188)
02-18 20:32:01.367  3739  3739 E AndroidRuntime: 	at com.crashlytics.android.Crashlytics.checkInitialized(Crashlytics.java:371)
02-18 20:32:01.367  3739  3739 E AndroidRuntime: 	at com.crashlytics.android.Crashlytics.logException(Crashlytics.java:207)
02-18 20:32:01.367  3739  3739 E AndroidRuntime: 	at org.apache.cordova.firebase.FirebasePlugin$14.run(FirebasePlugin.java:509)

**Comment by guylando** [comment]
I think it happens when calling setCrashlyticsUserId after app loaded. Supposed to call something additional before calling setCrashlyticsUserId?

**Comment by guylando** [comment]
The reason is that the other plugin calls Fabric.with without adding crashlytics.
