### ISSUE TITLE
Crash invoked, but no crash reports in firebase

### ISSUE THREAD

**Issue by therepo90** [arnesson/cordova-plugin-firebase#1023]
**Describe the bug**
Im using the latest version of cordova-plugin-firebase and invoking crash, getting stack:
FATAL EXCEPTION: main
    Process: com.myapp, PID: 10318
    java.lang.RuntimeException: This is a crash
        at com.appcrash.plugin.AppCrash$1.run(AppCrash.java:29)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

But no error present in crashlytics.
All other firebase functionalities work, app is configured both in console panel at firebase and in project.

**Comment by sagrawal31** [comment]
Same here. I'm confused if this plugin is even tracking crash analytics to Firebase

**Comment by santanu1122** [comment]
I have found something similer with extra details - 
Bad notification for startForeground: java.lang.RuntimeException: invalid channel for service notification: Notification(channel=null pri=-2 contentView=null vibrate=null sound=null defaults=0x0 flags=0x42 color=0x00000000 number=0 vis=PRIVATE semFlags=0x0 semPriority=0 semMissedCount=0)
The issue is happening in mostly 8.1.0 version.

@therepo90 , found any solution yet?
