### ISSUE TITLE
Error When Running On Android

### ISSUE THREAD

**Issue by Chuckv01** [arnesson/cordova-plugin-firebase#2]
First off, thanks for pioneering this!

Having a little trouble getting off the ground after installing the plugin. What I've I done:

1. Installed the plugin using this command: `cordova plugin add https://github.com/arnesson/cordova-plugin-firebase.git --variable AD_UNIT_ID_FOR_BANNER_TEST="toBeFilledInLater" --variable AD_UNIT_ID_FOR_INTERSTITIAL_TEST="toBeFilledInLater" --variable CLIENT_ID="toBeFilledInLater" --variable REVERSED_CLIENT_ID="toBeFilledInLater" --variable API_KEY="toBeFilledInLater" --variable GCM_SENDER_ID="toBeFilledInLater" --variable BUNDLE_ID="toBeFilledInLater" --variable PROJECT_ID="toBeFilledInLater" --variable STORAGE_BUCKET="toBeFilledInLater" --variable GOOGLE_APP_ID="toBeFilledInLater" --variable DATABASE_URL="toBeFilledInLater"`
2. Added my app's values into `plugins/cordova-firebase-plugin/plugin.xml`. 

When I attempt to run on android I am getting these errors reported via logcat:

```
W/System.err( 8000): java.lang.ClassNotFoundException: cordova-plugin-firebase.FirebasePlugin
W/System.err( 8000): 	at java.lang.Class.classForName(Native Method)
W/System.err( 8000): 	at java.lang.Class.forName(Class.java:308)
W/System.err( 8000): 	at java.lang.Class.forName(Class.java:272)
W/System.err( 8000): 	at org.apache.cordova.PluginManager.instantiatePlugin(PluginManager.java:490)
W/System.err( 8000): 	at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:170)
W/System.err( 8000): 	at org.apache.cordova.PluginManager.startupPlugins(PluginManager.java:98)
W/System.err( 8000): 	at org.apache.cordova.PluginManager.init(PluginManager.java:87)
W/System.err( 8000): 	at org.apache.cordova.CordovaWebViewImpl.init(CordovaWebViewImpl.java:116)
W/System.err( 8000): 	at org.apache.cordova.CordovaActivity.init(CordovaActivity.java:144)
W/System.err( 8000): 	at org.apache.cordova.CordovaActivity.loadUrl(CordovaActivity.java:214)
W/System.err( 8000): 	at com.vandersw.pullupchallenge.MainActivity.onCreate(MainActivity.java:32)
W/System.err( 8000): 	at android.app.Activity.performCreate(Activity.java:5958)
W/System.err( 8000): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1129)
W/System.err( 8000): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2364)
W/System.err( 8000): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2474)
W/System.err( 8000): 	at android.app.ActivityThread.access$800(ActivityThread.java:144)
W/System.err( 8000): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1359)
W/System.err( 8000): 	at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err( 8000): 	at android.os.Looper.loop(Looper.java:155)
W/System.err( 8000): 	at android.app.ActivityThread.main(ActivityThread.java:5696)
W/System.err( 8000): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 8000): 	at java.lang.reflect.Method.invoke(Method.java:372)
W/System.err( 8000): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1028)
W/System.err( 8000): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
W/System.err( 8000): Caused by: java.lang.ClassNotFoundException: Didn't find class "cordova-plugin-firebase.FirebasePlugin" on path: DexPathList[[zip file "/data/app/com.vandersw.pullupchallenge-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
W/System.err( 8000): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
W/System.err( 8000): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
W/System.err( 8000): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
W/System.err( 8000): 	... 24 more
W/System.err( 8000): 	Suppressed: java.lang.ClassNotFoundException: cordova-plugin-firebase.FirebasePlugin
W/System.err( 8000): 		at java.lang.Class.classForName(Native Method)
W/System.err( 8000): 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
W/ActivityManager(  680):   Force finishing activity com.vandersw.pullupchallenge/.MainActivity
W/System.err( 8000): 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
W/System.err( 8000): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
W/System.err( 8000): 		... 25 more
W/System.err( 8000): 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
I/System.out( 8000): Error adding plugin cordova-plugin-firebase.FirebasePlugin.
D/StatusBarManagerService(  680): setSystemUiVisibility(0x8600)
E/AndroidRuntime( 8000): FATAL EXCEPTION: main
E/AndroidRuntime( 8000): Process: com.vandersw.pullupchallenge, PID: 8000
E/AndroidRuntime( 8000): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.vandersw.pullupchallenge/com.vandersw.pullupchallenge.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CordovaPlugin.privateInitialize(java.lang.String, org.apache.cordova.CordovaInterface, org.apache.cordova.CordovaWebView, org.apache.cordova.CordovaPreferences)' on a null object reference
E/AndroidRuntime( 8000): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2411)
E/AndroidRuntime( 8000): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2474)
E/AndroidRuntime( 8000): 	at android.app.ActivityThread.access$800(ActivityThread.java:144)
E/AndroidRuntime( 8000): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1359)
E/AndroidRuntime( 8000): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 8000): 	at android.os.Looper.loop(Looper.java:155)
E/AndroidRuntime( 8000): 	at android.app.ActivityThread.main(ActivityThread.java:5696)
E/AndroidRuntime( 8000): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 8000): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 8000): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1028)
E/AndroidRuntime( 8000): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
E/AndroidRuntime( 8000): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CordovaPlugin.privateInitialize(java.lang.String, org.apache.cordova.CordovaInterface, org.apache.cordova.CordovaWebView, org.apache.cordova.CordovaPreferences)' on a null object reference
E/AndroidRuntime( 8000): 	at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:172)
E/AndroidRuntime( 8000): 	at org.apache.cordova.PluginManager.startupPlugins(PluginManager.java:98)
E/AndroidRuntime( 8000): 	at org.apache.cordova.PluginManager.init(PluginManager.java:87)
E/AndroidRuntime( 8000): 	at org.apache.cordova.CordovaWebViewImpl.init(CordovaWebViewImpl.java:116)
E/AndroidRuntime( 8000): 	at org.apache.cordova.CordovaActivity.init(CordovaActivity.java:144)
E/AndroidRuntime( 8000): 	at org.apache.cordova.CordovaActivity.loadUrl(CordovaActivity.java:214)
E/AndroidRuntime( 8000): 	at com.vandersw.pullupchallenge.MainActivity.onCreate(MainActivity.java:32)
E/AndroidRuntime( 8000): 	at android.app.Activity.performCreate(Activity.java:5958)
E/AndroidRuntime( 8000): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1129)
E/AndroidRuntime( 8000): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2364)
E/AndroidRuntime( 8000): 	... 10 more
D/StatusBarManagerService(  680): manageDisableList userId=0 what=0x0 pkg=WindowManager.LayoutParams
E/ActivityManager(  680): App crashed! Process: com.vandersw.pullupchallenge

```

**Comment by robertarnesson** [comment]
fixed in ac21300

**Comment by robertarnesson** [comment]
also should not edit plugins/cordova-firebase-plugin/plugin.xml. you should put the variables in your app's config.xml

**Comment by robertarnesson** [comment]
also just FYI, the GOOGLE_APP_ID has "ios" and "android" in them, e.g. 1:123456789012:ios:abcdefghijklmnop. I need to handle this in the hook that writes the config file but havent got to fixing it yet (also im just testing on ios right now). If you test on android you may need to update this to the android value

**Comment by Chuckv01** [comment]
@robertarnesson Thanks! Yeah I've fixed a few things on the Android side. Been working on a fork to add analytics. (https://github.com/Chuckv01/cordova-plugin-firebase) I've separated the config variables into ios and android versions. Seems they differ on more than just the GOOGLE_APP_ID. Will submit a pull request in a bit.

**Comment by robertarnesson** [comment]
yes you are right there are more. I think the way to go is to have two variables with the path to google-services.json and GoogleService-Info.plist and have the hook copy them to the right place. Wish there was some way to do that with plugin.xml/config.xml but there is not
