### ISSUE TITLE
App crash: Firebase API initialization failure.

### ISSUE THREAD

**Issue by salouri** [arnesson/cordova-plugin-firebase#216]
After installing the plugin I was able to build on android successfully but the app crashes with "Firebase API initialization failure." error. Adb log shows the below

D/FirebaseApp: com.google.firebase.auth.FirebaseAuth is not linked. Skipping initialization.
D/FirebaseInstanceId: Restricting intent to a specific service: org.apache.cordova.firebase.FirebasePluginInstanceIDService
E/ActivityThread: Failed to find provider info for com.google.android.gms.chimera
W/DynamiteModule: Failed to retrieve remote module version.
 E/FirebaseApp: Firebase API initialization failure.
                                                                 java.lang.reflect.InvocationTargetException
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.google.firebase.FirebaseApp.zza(Unknown Source)
                                                                     at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
                                                                     at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
                                                                     at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
                                                                     at com.google.firebase.provider.FirebaseInitProvider.onCreate(Unknown Source)
                                                                     at android.content.ContentProvider.attachInfo(ContentProvider.java:1801)
                                                                     at android.content.ContentProvider.attachInfo(ContentProvider.java:1776)
                                                                     at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source)
                                                                     at android.app.ActivityThread.installProvider(ActivityThread.java:5454)
                                                                     at android.app.ActivityThread.installContentProviders(ActivityThread.java:5025)
                                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4965)
                                                                     at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
                                                                     at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:334)
                                                                     at android.app.ActivityThread.handleBindApplication(<Xposed>)
                                                                     at android.app.ActivityThread.-wrap1(ActivityThread.java)
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1554)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                     at android.os.Looper.loop(Looper.java:207)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5769)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
                                                                     at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
                                                                  Caused by: java.lang.IllegalStateException: The meta-data tag in your app's AndroidManifest.xml does not have the right value.  Expected 10298000 but found 5089000.  You must have the following declaration within the <application> element:     <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />
                                                                     at com.google.android.gms.common.zzg.zzaH(Unknown Source)
                                                                     at com.google.android.gms.common.zzg.isGooglePlayServicesAvailable(Unknown Source)
                                                                     at com.google.android.gms.common.zze.isGooglePlayServicesAvailable(Unknown Source)
                                                                     at com.google.android.gms.dynamite.DynamiteModule.zzbm(Unknown Source)
                                                                     at com.google.android.gms.dynamite.DynamiteModule.zzc(Unknown Source)
                                                                     at com.google.android.gms.dynamite.DynamiteModule.zzb(Unknown Source)
                                                                     at com.google.android.gms.dynamite.DynamiteModule$1.zzb(Unknown Source)
                                                                     at com.google.android.gms.dynamite.DynamiteModule$6.zza(Unknown Source)
                                                                     at com.google.android.gms.dynamite.DynamiteModule.zza(Unknown Source)
                                                                     at com.google.android.gms.internal.zzaqc.initialize(Unknown Source)
                                                                     at com.google.android.gms.internal.zzaqb.initialize(Unknown Source)
                                                                     at com.google.android.gms.internal.zzbns.initialize(Unknown Source)
                                                                     at com.google.firebase.crash.FirebaseCrash.getInstance(Unknown Source)
                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                     at com.google.firebase.FirebaseApp.zza(Unknown Source) 
                                                                     at com.google.firebase.FirebaseApp.initializeApp(Unknown Source) 
                                                                     at com.google.firebase.FirebaseApp.initializeApp(Unknown Source) 
                                                                     at com.google.firebase.FirebaseApp.initializeApp(Unknown Source) 
                                                                     at com.google.firebase.provider.FirebaseInitProvider.onCreate(Unknown Source) 
                                                                     at android.content.ContentProvider.attachInfo(ContentProvider.java:1801) 
                                                                     at android.content.ContentProvider.attachInfo(ContentProvider.java:1776) 
                                                                     at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source) 
                                                                     at android.app.ActivityThread.installProvider(ActivityThread.java:5454) 
                                                                     at android.app.ActivityThread.installContentProviders(ActivityThread.java:5025) 
                                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4965) 
                                                                     at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method) 
                                                                     at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:334) 
                                                                     at android.app.ActivityThread.handleBindApplication(<Xposed>) 
                                                                     at android.app.ActivityThread.-wrap1(ActivityThread.java) 
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1554) 
                                                                     at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                     at android.os.Looper.loop(Looper.java:207) 
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5769) 
                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789) 
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679) 
                                                                     at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102) `

My **build.gradle** file is as follows:

`apply plugin: 'com.android.application'

buildscript {
    repositories {
        jcenter()
        mavenCentral()

    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.0'
    }
   }

// Allow plugins to declare Maven dependencies via build-extras.gradle.
repositories {
    jcenter()
    mavenCentral()

}

task wrapper(type: Wrapper) {
    gradleVersion = '2.8'
}

ext {
    apply from: 'CordovaLib/cordova.gradle'
    // The value for android.compileSdkVersion.
    if (!project.hasProperty('cdvCompileSdkVersion')) {
        cdvCompileSdkVersion = null;
    }
    // The value for android.buildToolsVersion.
    if (!project.hasProperty('cdvBuildToolsVersion')) {
        cdvBuildToolsVersion = null;
    }
    // Sets the versionCode to the given value.
    if (!project.hasProperty('cdvVersionCode')) {
        cdvVersionCode = null
    }
    // Sets the minSdkVersion to the given value.
    if (!project.hasProperty('cdvMinSdkVersion')) {
        cdvMinSdkVersion = null
    }
    // Whether to build architecture-specific APKs.
    if (!project.hasProperty('cdvBuildMultipleApks')) {
        cdvBuildMultipleApks = null
    }
    // .properties files to use for release signing.
    if (!project.hasProperty('cdvReleaseSigningPropertiesFile')) {
        cdvReleaseSigningPropertiesFile = null
    }
    // .properties files to use for debug signing.
    if (!project.hasProperty('cdvDebugSigningPropertiesFile')) {
        cdvDebugSigningPropertiesFile = null
    }
    // Set by build.js script.
    if (!project.hasProperty('cdvBuildArch')) {
        cdvBuildArch = null
    }

    // Plugin gradle extensions can append to this to have code run at the end.
    cdvPluginPostBuildExtras = []
}

// PLUGIN GRADLE EXTENSIONS START
**apply from: "cordova-plugin-firebase/alquran-build.gradle"**
// PLUGIN GRADLE EXTENSIONS END

def hasBuildExtras = file('build-extras.gradle').exists()
if (hasBuildExtras) {
    apply from: 'build-extras.gradle'
}

// Set property defaults after extension .gradle files.
if (ext.cdvCompileSdkVersion == null) {
    ext.cdvCompileSdkVersion = privateHelpers.getProjectTarget()
}
if (ext.cdvBuildToolsVersion == null) {
    ext.cdvBuildToolsVersion = privateHelpers.findLatestInstalledBuildTools()
}
if (ext.cdvDebugSigningPropertiesFile == null && file('debug-signing.properties').exists()) {
    ext.cdvDebugSigningPropertiesFile = 'debug-signing.properties'
}
if (ext.cdvReleaseSigningPropertiesFile == null && file('release-signing.properties').exists()) {
    ext.cdvReleaseSigningPropertiesFile = 'release-signing.properties'
}

// Cast to appropriate types.
ext.cdvBuildMultipleApks = cdvBuildMultipleApks == null ? false : cdvBuildMultipleApks.toBoolean();
ext.cdvMinSdkVersion = cdvMinSdkVersion == null ? null : Integer.parseInt('' + cdvMinSdkVersion)
ext.cdvVersionCode = cdvVersionCode == null ? null : Integer.parseInt('' + cdvVersionCode)

def computeBuildTargetName(debugBuild) {
    def ret = 'assemble'
    if (cdvBuildMultipleApks && cdvBuildArch) {
        def arch = cdvBuildArch == 'arm' ? 'armv7' : cdvBuildArch
        ret += '' + arch.toUpperCase().charAt(0) + arch.substring(1);
    }
    return ret + (debugBuild ? 'Debug' : 'Release')
}

// Make cdvBuild a task that depends on the debug/arch-sepecific task.
task cdvBuildDebug
cdvBuildDebug.dependsOn {
    return computeBuildTargetName(true)
}

task cdvBuildRelease
cdvBuildRelease.dependsOn {
    return computeBuildTargetName(false)
}

task cdvPrintProps << {
    println('cdvCompileSdkVersion=' + cdvCompileSdkVersion)
    println('cdvBuildToolsVersion=' + cdvBuildToolsVersion)
    println('cdvVersionCode=' + cdvVersionCode)
    println('cdvMinSdkVersion=' + cdvMinSdkVersion)
    println('cdvBuildMultipleApks=' + cdvBuildMultipleApks)
    println('cdvReleaseSigningPropertiesFile=' + cdvReleaseSigningPropertiesFile)
    println('cdvDebugSigningPropertiesFile=' + cdvDebugSigningPropertiesFile)
    println('cdvBuildArch=' + cdvBuildArch)
    println('computedVersionCode=' + android.defaultConfig.versionCode)
    android.productFlavors.each { flavor ->
        println('computed' + flavor.name.capitalize() + 'VersionCode=' + flavor.versionCode)
    }
}

android {
    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            java.srcDirs = ['src']
            resources.srcDirs = ['src']
            aidl.srcDirs = ['src']
            renderscript.srcDirs = ['src']
            res.srcDirs = ['res']
            assets.srcDirs = ['assets']
            jniLibs.srcDirs = ['libs']
        }
    }
	useLibrary  'org.apache.http.legacy'
        
    defaultConfig {
    	multiDexEnabled true
       // versionCode cdvVersionCode ?: Integer.parseInt("" + privateHelpers.extractIntFromManifest("versionCode") + "0")
        versionCode cdvVersionCode ?: Integer.parseInt("" + privateHelpers.extractIntFromManifest("versionCode"))
        //applicationId privateHelpers.extractStringFromManifest("package")
        applicationId "com.qquest.alquran"
        if (cdvMinSdkVersion != null) {
            minSdkVersion cdvMinSdkVersion
        }
        ndk {
           abiFilters "armeabi", "armeabi-v7a", "x86", "mips"
        }
    }

    lintOptions {
      abortOnError false;
    }

    compileSdkVersion cdvCompileSdkVersion
    buildToolsVersion cdvBuildToolsVersion

    if (Boolean.valueOf(cdvBuildMultipleApks)) {
        productFlavors {
            armv7 {
                versionCode defaultConfig.versionCode + 2
                ndk {
                    abiFilters "armeabi-v7a", ""
                }
            }
            x86 {
                versionCode defaultConfig.versionCode + 4
                ndk {
                    abiFilters "x86", ""
                }
            }
            all {
                ndk {
                    abiFilters "all", ""
                }
            }
        }
    } else if (!cdvVersionCode) {
      def minSdkVersion = cdvMinSdkVersion ?: privateHelpers.extractIntFromManifest("minSdkVersion")
      // Vary versionCode by the two most common API levels:
      // 14 is ICS, which is the lowest API level for many apps.
      // 20 is Lollipop, which is the lowest API level for the updatable system webview.
      if (minSdkVersion >= 20) {
        defaultConfig.versionCode += 9
      } else if (minSdkVersion >= 14) {
      //  defaultConfig.versionCode += 8
      }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_6
        targetCompatibility JavaVersion.VERSION_1_6
    }

    if (cdvReleaseSigningPropertiesFile) {
        signingConfigs {
            release {
                // These must be set or Gradle will complain (even if they are overridden).
                keyAlias = ""
                keyPassword = "__unset"
                // And these must be set to non-empty in order to have the signing step added to the task graph.
                storeFile = null
                storePassword = "__unset"
            }
        }
        buildTypes {
            release {
                minifyEnabled false
                proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
                signingConfig signingConfigs.release
            }
        }
        addSigningProps(cdvReleaseSigningPropertiesFile, signingConfigs.release)
    }
    if (cdvDebugSigningPropertiesFile) {
        addSigningProps(cdvDebugSigningPropertiesFile, signingConfigs.debug)
    }
}

dependencies {
    compile fileTree(include: '*.jar', dir: 'libs')
    **// SUB-PROJECT DEPENDENCIES START**
    **debugCompile project(path: "CordovaLib", configuration: "debug")
    releaseCompile project(path: "CordovaLib", configuration: "release")
   compile "com.google.android.gms:play-services-ads:+"
   compile "com.android.support:support-v13:+"
   compile "com.android.support:support-v4:+"
    compile project(':PdCore')
    compile project(':downloader_library')
    compile project(':market_licensing')
    compile project(':zip_file')
    compile "com.google.firebase:firebase-core:+"
    compile "com.google.firebase:firebase-messaging:+"
    compile "com.google.firebase:firebase-crash:+"
    compile "com.google.firebase:firebase-config:+"**
    **// SUB-PROJECT DEPENDENCIES END
}**

def promptForReleaseKeyPassword() {
    if (!cdvReleaseSigningPropertiesFile) {
        return;
    }
    if ('__unset'.equals(android.signingConfigs.release.storePassword)) {
        android.signingConfigs.release.storePassword = privateHelpers.promptForPassword('Enter key store password: ')
    }
    if ('__unset'.equals(android.signingConfigs.release.keyPassword)) {
        android.signingConfigs.release.keyPassword = privateHelpers.promptForPassword('Enter key password: ');
    }
}

gradle.taskGraph.whenReady { taskGraph ->
    taskGraph.getAllTasks().each() { task ->
        if (task.name == 'validateReleaseSigning') {
            promptForReleaseKeyPassword()
        }
    }
}

def addSigningProps(propsFilePath, signingConfig) {
    def propsFile = file(propsFilePath)
    def props = new Properties()
    propsFile.withReader { reader ->
        props.load(reader)
    }

    def storeFile = new File(props.get('key.store') ?: privateHelpers.ensureValueExists(propsFilePath, props, 'storeFile'))
    if (!storeFile.isAbsolute()) {
        storeFile = RelativePath.parse(true, storeFile.toString()).getFile(propsFile.getParentFile())
    }
    if (!storeFile.exists()) {
        throw new FileNotFoundException('Keystore file does not exist: ' + storeFile.getAbsolutePath())
    }
    signingConfig.keyAlias = props.get('key.alias') ?: privateHelpers.ensureValueExists(propsFilePath, props, 'keyAlias')
    signingConfig.keyPassword = props.get('keyPassword', props.get('key.alias.password', signingConfig.keyPassword))
    signingConfig.storeFile = storeFile
    signingConfig.storePassword = props.get('storePassword', props.get('key.store.password', signingConfig.storePassword))
    def storeType = props.get('storeType', props.get('key.store.type', ''))
    if (!storeType) {
        def filename = storeFile.getName().toLowerCase();
        if (filename.endsWith('.p12') || filename.endsWith('.pfx')) {
            storeType = 'pkcs12'
        } else {
            storeType = signingConfig.storeType // "jks"
        }
    }
    signingConfig.storeType = storeType
}

for (def func : cdvPluginPostBuildExtras) {
    func()
}
if (hasProperty('postBuildExtras')) {
    postBuildExtras()
}
`

I tried many possible solutions like in [here](http://stackoverflow.com/questions/37724761/android-firebaseapp-firebase-initialization-is-not-starting), [here](https://github.com/firebase/quickstart-android/issues/24) , [here](http://stackoverflow.com/questions/39085586/firebase-api-initialization-failure)  and [here](http://stackoverflow.com/questions/37396973/how-to-solve-firebase-api-initialization-failure-android-firebase); without any luck ... 
what could be wrong?

**Comment by tuchangwei** [comment]
Crash too

**Comment by robertarnesson** [comment]
closing this for now. if its still an issue (try using master) then open a new ticket

**Comment by joshbabb** [comment]
We are encountering this exact issue now.
