### ISSUE TITLE
Error: Cannot read property 'Plugin' of undefined, resolving symbol Firebase in **/node_modules/@ionic-native/firebase/index.d.ts 

### ISSUE THREAD

**Issue by senthil7273** [arnesson/cordova-plugin-firebase#221]
**ionic build android --release**
makes the android build perfectly

When i try
 **build android --prod --release**

i am getting the error

[22:37:02]  ionic-app-scripts 1.2.2 
[22:37:02]  build prod started ... 
[22:37:02]  clean started ... 
[22:37:02]  clean finished in 2 ms 
[22:37:02]  copy started ... 
[22:37:02]  ngc started ... 
can't resolve module @ionic-native/core from /Users/yokks/Documents/apps/NammaAlangulam/node_modules/@ionic-native/firebase/index.d.ts
[22:37:03]  ionic-app-script task: "build" 
[22:37:03]  Error: Cannot read property 'Plugin' of undefined, resolving symbol Firebase in 
            /Users/yokks/Documents/apps/NammaAlangulam/node_modules/@ionic-native/firebase/index.d.ts 
Error: Cannot read property 'Plugin' of undefined, resolving symbol Firebase in /Users/yokks/Documents/apps/NammaAlangulam/node_modules/@ionic-native/firebase/index.d.ts
    at simplifyInContext (/Users/yokks/Documents/apps/NammaAlangulam/node_modules/@angular/compiler-cli/src/static_reflector.js:475:23)
    at StaticReflector.simplify (/Users/yokks/Documents/apps/NammaAlangulam/node_modules/@angular/compiler-cli/src/static_reflector.js:478:22)
    at StaticReflector.annotations (/Users/yokks/Documents/apps/NammaAlangulam/node_modules/@angular/compiler-cli/src/static_reflector.js:60:36)
    at NgModuleResolver.resolve (/Users/yokks/Documents/apps/NammaAlangulam/node_modules/@angular/compiler/bundles/compiler.umd.js:14261:46)
    at CompileMetadataResolver._loadNgModuleMetadata (/Users/yokks/Documents/apps/NammaAlangulam/node_modules/@angular/compiler/bundles/compiler.umd.js:14646:45)
    at CompileMetadataResolver.getUnloadedNgModuleMetadata (/Users/yokks/Documents/apps/NammaAlangulam/node_modules/@angular/compiler/bundles/compiler.umd.js:14636:23)
    at addNgModule (/Users/yokks/Documents/apps/NammaAlangulam/node_modules/@angular/compiler/bundles/compiler.umd.js:12944:43)
    at /Users/yokks/Documents/apps/NammaAlangulam/node_modules/@angular/compiler/bundles/compiler.umd.js:12957:16
    at Array.forEach (native)
    at _createNgModules (/Users/yokks/Documents/apps/NammaAlangulam/node_modules/@angular/compiler/bundles/compiler.umd.js:12956:28)

npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/Cellar/node/7.6.0/bin/node" "/usr/local/bin/npm" "run" "ionic:build" "--" "--prod" "--release"
npm ERR! node v7.6.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE

**Comment by senthil7273** [comment]
used package.json is 
{
  "name": "ionic-hello-world",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/common": "2.2.1",
    "@angular/compiler": "2.2.1",
    "@angular/compiler-cli": "2.2.1",
    "@angular/core": "2.2.1",
    "@angular/forms": "2.2.1",
    "@angular/http": "2.2.1",
    "@angular/platform-browser": "2.2.1",
    "@angular/platform-browser-dynamic": "2.2.1",
    "@angular/platform-server": "2.2.1",
    "@ionic-native/core": "^3.3.0",
    "@ionic-native/firebase": "3.3.0",
    "@ionic/storage": "1.1.7",
    "@ngx-translate/core": "^6.0.1",
    "@ngx-translate/http-loader": "0.0.3",
    "angularfire2": "^2.0.0-beta.8",
    "firebase": "^3.7.3",
    "ionic-angular": "2.0.1",
    "ionic-native": "2.4.1",
    "ionicons": "3.0.0",
    "ng2-translate": "^5.0.0",
    "rxjs": "5.0.0-beta.12",
    "sw-toolbox": "3.4.0",
    "zone.js": "0.6.26"
  },
  "devDependencies": {
    "@ionic/app-scripts": "^1.2.2",
    "typescript": "2.0.9"
  },
  "cordovaPlugins": [
    "cordova-plugin-statusbar",
    "cordova-plugin-splashscreen",
    "cordova-plugin-console",
    "cordova-plugin-whitelist",
    "cordova-plugin-device",
    "ionic-plugin-keyboard"
  ],
  "cordovaPlatforms": [
    "ios",
    {
      "platform": "ios",
      "version": "",
      "locator": "ios"
    }
  ],
  "description": "NammaAlangulam: An Ionic project"
}

**Comment by robertarnesson** [comment]
this is an issue for ionic native
