### ISSUE TITLE
Features don't work - 'apply' undefined

### ISSUE THREAD

**Issue by sasos90** [arnesson/cordova-plugin-firebase#224]
Hey guys!

I get next javascript errors in the console.
I am using IONIC2 so I installed the plugin over "ionic plugin add..." version 0.1.19.
And the thing is that onTokenRefresh method works but setScreenName fails. I assume that is not supported from firebase at all right?
Does anyone has a clue what is going on here? Thanks in advance!

My Ionic info output looks like this:

> Cordova CLI: 6.5.0 
> Ionic Framework Version: 2.3.0
> Ionic CLI Version: 2.1.18
> Ionic App Lib Version: 2.1.9
> Ionic App Scripts Version: 1.1.4
> ios-deploy version: Not installed
> ios-sim version: Not installed
> OS: Linux 4.4
> Node Version: v7.2.1
> Xcode version: Not installed

```
main.js:76123 EXCEPTION: Uncaught (in promise): TypeError: Cannot read property 'apply' of undefined
TypeError: Cannot read property 'apply' of undefined
    at callCordovaPlugin (file:///android_asset/www/build/main.js:82676:42)
    at file:///android_asset/www/build/main.js:82686:24
    at file:///android_asset/www/build/main.js:57143:17
    at new t (file:///android_asset/www/build/polyfills.js:3:11969)
    at tryNativePromise (file:///android_asset/www/build/main.js:57142:20)
    at getPromise (file:///android_asset/www/build/main.js:57150:12)
    at wrapPromise (file:///android_asset/www/build/main.js:82685:93)
    at Firebase.<anonymous> (file:///android_asset/www/build/main.js:82797:20)
    at Firebase.value [as hasPermission] (file:///android_asset/www/build/main.js:116219:125)
    at file:///android_asset/www/build/main.js:116393:37
    at t.invoke (file:///android_asset/www/build/polyfills.js:3:9655)
    at Object.onInvoke (file:///android_asset/www/build/main.js:37150:37)
    at t.invoke (file:///android_asset/www/build/polyfills.js:3:9606)
    at e.run (file:///android_asset/www/build/polyfills.js:3:7019)
    at file:///android_asset/www/build/polyfills.js:3:4661ErrorHandler.handleError @ main.js:76123IonicErrorHandler.handleError @ main.js:124781next @ main.js:51128schedulerFn @ main.js:53184SafeSubscriber.__tryOrUnsub @ main.js:101171SafeSubscriber.next @ main.js:101120Subscriber._next @ main.js:101073Subscriber.next @ main.js:101037Subject.next @ main.js:44771EventEmitter.emit @ main.js:53170NgZone.triggerError @ main.js:37210onHandleError @ main.js:37171t.handleError @ polyfills.js:3e.runGuarded @ polyfills.js:3r @ polyfills.js:3i @ polyfills.js:3
main.js:76128 ORIGINAL STACKTRACE:ErrorHandler.handleError @ main.js:76128IonicErrorHandler.handleError @ main.js:124781next @ main.js:51128schedulerFn @ main.js:53184SafeSubscriber.__tryOrUnsub @ main.js:101171SafeSubscriber.next @ main.js:101120Subscriber._next @ main.js:101073Subscriber.next @ main.js:101037Subject.next @ main.js:44771EventEmitter.emit @ main.js:53170NgZone.triggerError @ main.js:37210onHandleError @ main.js:37171t.handleError @ polyfills.js:3e.runGuarded @ polyfills.js:3r @ polyfills.js:3i @ polyfills.js:3
main.js:76129 Error: Uncaught (in promise): TypeError: Cannot read property 'apply' of undefined
TypeError: Cannot read property 'apply' of undefined
    at callCordovaPlugin (file:///android_asset/www/build/main.js:82676:42)
    at file:///android_asset/www/build/main.js:82686:24
    at file:///android_asset/www/build/main.js:57143:17
    at new t (file:///android_asset/www/build/polyfills.js:3:11969)
    at tryNativePromise (file:///android_asset/www/build/main.js:57142:20)
    at getPromise (file:///android_asset/www/build/main.js:57150:12)
    at wrapPromise (file:///android_asset/www/build/main.js:82685:93)
    at Firebase.<anonymous> (file:///android_asset/www/build/main.js:82797:20)
    at Firebase.value [as hasPermission] (file:///android_asset/www/build/main.js:116219:125)
    at file:///android_asset/www/build/main.js:116393:37
    at t.invoke (file:///android_asset/www/build/polyfills.js:3:9655)
    at Object.onInvoke (file:///android_asset/www/build/main.js:37150:37)
    at t.invoke (file:///android_asset/www/build/polyfills.js:3:9606)
    at e.run (file:///android_asset/www/build/polyfills.js:3:7019)
    at file:///android_asset/www/build/polyfills.js:3:4661
    at new Error (native)
    at Error.v (file:///android_asset/www/build/polyfills.js:3:4864)
    at s (file:///android_asset/www/build/polyfills.js:3:4289)
    at new t (file:///android_asset/www/build/polyfills.js:3:11995)
    at tryNativePromise (file:///android_asset/www/build/main.js:57142:20)
    at getPromise (file:///android_asset/www/build/main.js:57150:12)
    at wrapPromise (file:///android_asset/www/build/main.js:82685:93)
    at Firebase.<anonymous> (file:///android_asset/www/build/main.js:82797:20)
    at Firebase.value [as hasPermission] (file:///android_asset/www/build/main.js:116219:125)
    at file:///android_asset/www/build/main.js:116393:37
    at t.invoke (file:///android_asset/www/build/polyfills.js:3:9655)
    at Object.onInvoke (file:///android_asset/www/build/main.js:37150:37)
    at t.invoke (file:///android_asset/www/build/polyfills.js:3:9606)
    at e.run (file:///android_asset/www/build/polyfills.js:3:7019)
    at file:///android_asset/www/build/polyfills.js:3:4661
```

**Comment by robertarnesson** [comment]
should be fixed in 0.1.20
