### ISSUE TITLE
Error on after_prepare

### ISSUE THREAD

**Issue by ahar** [arnesson/cordova-plugin-firebase#361]
Hi, 

I got error while building android application. After creating directory Resources in directory 
"platforms/ios/projectName/" everything works fine. Could you please add checking if directory exists before writing to that directory. 

Thanks

Prepared android project successfully
Executing script found in plugin cordova-plugin-firebase for hook "after_prepare": plugins/cordova-plugin-firebase/scripts/after_prepare.js
Error: TypeError: invalid data
    at WriteStream.Socket.write (net.js:617:11)
    at WriteStream.stream.write (/usr/local/lib/node_modules/cordova/node_modules/ansi/lib/newlines.js:36:21)
    at Object.<anonymous> (/____/mobile/phonegap/plugins/cordova-plugin-firebase/scripts/after_prepare.js:46:24)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at runScriptViaModuleLoader (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:179:20)

**Comment by dobbinx3** [comment]
Hi there, it seems you have the same problem as pointed in #349 

I already made a pull request #351 to check if the folder exists.

Cya.

**Comment by robertarnesson** [comment]
fixed now in master
