### ISSUE TITLE
Getting Error on Application Launch

### ISSUE THREAD

**Issue by dhruv270** [arnesson/cordova-plugin-firebase#5]
Hey, thanks for FCM plugin.
I am facing one issue on app launch in Cordova. Please help me to solve this issue. Here is the my logcat.
```
06-27 18:41:29.552: E/AndroidRuntime(28330): FATAL EXCEPTION: main
06-27 18:41:29.552: E/AndroidRuntime(28330): Process: xxx.xxx.xxx, PID: 28330
06-27 18:41:29.552: E/AndroidRuntime(28330): java.lang.RuntimeException: Unable to start activity ComponentInfo{xxx.xxx.xxx/xxx.xxx.xxx.MainActivity}: java.lang.IllegalStateException: FirebaseApp with name [DEFAULT] doesn't exist. 
06-27 18:41:29.552: E/AndroidRuntime(28330): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2521)
06-27 18:41:29.552: E/AndroidRuntime(28330): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2595)
06-27 18:41:29.552: E/AndroidRuntime(28330): 	at android.app.ActivityThread.access$800(ActivityThread.java:178)
06-27 18:41:29.552: E/AndroidRuntime(28330): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1470)
06-27 18:41:29.552: E/AndroidRuntime(28330): 	at android.os.Handler.dispatchMessage(Handler.java:111)
06-27 18:41:29.552: E/AndroidRuntime(28330): 	at android.os.Looper.loop(Looper.java:194)
06-27 18:41:29.552: E/AndroidRuntime(28330): 	at android.app.ActivityThread.main(ActivityThread.java:5631)
06-27 18:41:29.552: E/AndroidRuntime(28330): 	at java.lang.reflect.Method.invoke(Native Method)
06-27 18:41:29.552: E/AndroidRuntime(28330): 	at java.lang.reflect.Method.invoke(Method.java:372)
06-27 18:41:29.552: E/AndroidRuntime(28330): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
06-27 18:41:29.552: E/AndroidRuntime(28330): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
06-27 18:41:29.552: E/AndroidRuntime(28330): Caused by: java.lang.IllegalStateException: FirebaseApp with name [DEFAULT] doesn't exist. 
06-27 18:41:29.552: E/AndroidRuntime(28330): 	at com.google.firebase.FirebaseApp.getInstance(Unknown Source)
06-27 18:41:29.552: E/AndroidRuntime(28330): 	at com.google.firebase.FirebaseApp.getInstance(Unknown Source)
06-27 18:41:29.552: E/AndroidRuntime(28330): 	at com.google.firebase.iid.FirebaseInstanceId.getInstance(Unknown Source)
06-27 18:41:29.552: E/AndroidRuntime(28330): 	at com.google.firebase.messaging.FirebaseMessaging.getInstance(Unknown Source)
06-27 18:41:29.552: E/AndroidRuntime(28330): 	at com.gae.scaffolder.plugin.FCMPlugin.initialize(FCMPlugin.java:34)
06-27 18:41:29.552: E/AndroidRuntime(28330): 	at org.apache.cordova.CordovaPlugin.privateInitialize(CordovaPlugin.java:57)
06-27 18:41:29.552: E/AndroidRuntime(28330): 	at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:172)
06-27 18:41:29.552: E/AndroidRuntime(28330): 	at org.apache.cordova.PluginManager.startupPlugins(PluginManager.java:98)
06-27 18:41:29.552: E/AndroidRuntime(28330): 	at org.apache.cordova.PluginManager.init(PluginManager.java:87)
06-27 18:41:29.552: E/AndroidRuntime(28330): 	at org.apache.cordova.CordovaWebViewImpl.init(CordovaWebViewImpl.java:116)
06-27 18:41:29.552: E/AndroidRuntime(28330): 	at org.apache.cordova.CordovaActivity.init(CordovaActivity.java:144)
06-27 18:41:29.552: E/AndroidRuntime(28330): 	at org.apache.cordova.CordovaActivity.loadUrl(CordovaActivity.java:214)
06-27 18:41:29.552: E/AndroidRuntime(28330): 	at xxx.xxx.xxx.MainActivity.onCreate(MainActivity.java:32)
06-27 18:41:29.552: E/AndroidRuntime(28330): 	at android.app.Activity.performCreate(Activity.java:6092)
06-27 18:41:29.552: E/AndroidRuntime(28330): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112)
06-27 18:41:29.552: E/AndroidRuntime(28330): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2468)
06-27 18:41:29.552: E/AndroidRuntime(28330): 	... 10 more
```

**Comment by Chuckv01** [comment]
@dhruv270 Looks like you don't have the config files setup correctly. To fix this on the latest version of the plugin:

1. Copy your android config files to the root of your cordova project
2. Install the plugin
3. Run `cordova prepare`

That should fix the issue.
