### ISSUE TITLE
App crashes on request with no internet connection

### ISSUE THREAD

**Issue by derTuca** [arnesson/cordova-plugin-firebase#503]
Hi.
When I try to use Phone Verification on Android and there is no network connection, the app crashes with the following log:

> 12-13 18:07:23.609 9981-10041/? E/PlayCommon: [25271] com.google.android.play.a.h.a(500): Failed to connect to server: java.net.UnknownHostException: Unable to resolve host "play.googleapis.com": No address associated with hostname
12-13 18:07:23.641 7496-7496/<package-name> E/UncaughtException: java.lang.ClassCastException: com.google.firebase.FirebaseNetworkException cannot be cast to com.google.firebase.auth.FirebaseAuthException
                                                                   at org.apache.cordova.firebase.FirebasePlugin$23$1.onVerificationFailed(FirebasePlugin.java:645)
                                                                   at com.google.android.gms.internal.zzdvy.zza(Unknown Source)
                                                                   at com.google.android.gms.internal.zzdvz.run(Unknown Source)
                                                                   at android.os.Handler.handleCallback(Handler.java:751)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                   at android.os.Looper.loop(Looper.java:154)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:6776)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
12-13 18:07:23.739 3807-3878/? E/libprocessgroup: failed to kill 1 processes for processgroup 9297
12-13 18:07:23.905 7496-7496/<package-name> E/AndroidRuntime: FATAL EXCEPTION: main
                                                            Process: <package-name>, PID: 7496
                                                            java.lang.ClassCastException: com.google.firebase.FirebaseNetworkException cannot be cast to com.google.firebase.auth.FirebaseAuthException
                                                                at org.apache.cordova.firebase.FirebasePlugin$23$1.onVerificationFailed(FirebasePlugin.java:645)
                                                                at com.google.android.gms.internal.zzdvy.zza(Unknown Source)
                                                                at com.google.android.gms.internal.zzdvz.run(Unknown Source)
                                                                at android.os.Handler.handleCallback(Handler.java:751)
                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                at android.os.Looper.loop(Looper.java:154)
                                                                at android.app.ActivityThread.main(ActivityThread.java:6776)
                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

Am I missing something?

**Comment by mgrbose** [comment]
Looks like I am having the same issue..

**Comment by Hirbod** [comment]
same here. Ended up checking with network activity plugin to prevent connection without internet
