### ISSUE TITLE
when trying to install the plugin I get this error

### ISSUE THREAD

**Issue by Daniel3549** [arnesson/cordova-plugin-firebase#538]
```
cordova plugin add cordova-plugin-firebase@0.1.25 --save
Installing "cordova-plugin-firebase" for android
Error during processing of action! Attempting to revert...
Failed to install 'cordova-plugin-firebase': Error
    at copyNewFile (/home/desarrollador1/Proyectos/chat/platforms/android/cordova/lib/pluginHandlers.js:245:45)
    at install (/home/desarrollador1/Proyectos/chat/platforms/android/cordova/lib/pluginHandlers.js:43:17)
    at ActionStack.process (/home/desarrollador1/Proyectos/chat/platforms/android/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PluginManager.doOperation (/home/desarrollador1/Proyectos/chat/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:114:20)
    at PluginManager.addPlugin (/home/desarrollador1/Proyectos/chat/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:144:17)
    at /home/desarrollador1/Proyectos/chat/platforms/android/cordova/Api.js:243:74
    at _fulfilled (/home/desarrollador1/Proyectos/chat/platforms/android/cordova/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/home/desarrollador1/Proyectos/chat/platforms/android/cordova/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/home/desarrollador1/Proyectos/chat/platforms/android/cordova/node_modules/q/q.js:816:13)
    at /home/desarrollador1/Proyectos/chat/platforms/android/cordova/node_modules/q/q.js:570:49
(node:32372) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): [object Object]
(node:32372) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

node v8.6.0
npm v5.6.0

**Comment by robertarnesson** [comment]
you can try #552

**Comment by chadmilden** [comment]
Hi robert, this is not working: 
![image](https://user-images.githubusercontent.com/4099715/37170764-f6fadf22-22c8-11e8-8865-ecf56f1993eb.png)
