### ISSUE TITLE
cordova prepare fails with this plugin

### ISSUE THREAD

**Issue by rlz** [arnesson/cordova-plugin-firebase#581]
I'm getting this error message (cordova 8.0.0):

Preparing Firebase on Android
{ Error: ENOENT: no such file or directory, open 'platforms/android/res/values/strings.xml'
    at Object.fs.openSync (fs.js:663:18)
    at Object.fs.readFileSync (fs.js:568:33)
    at updateStringsXml (/Users/rlz/projects/MenApp-cordova/plugins/cordova-plugin-firebase/scripts/after_prepare.js:57:22)
    at copyKey (/Users/rlz/projects/MenApp-cordova/plugins/cordova-plugin-firebase/scripts/after_prepare.js:94:29)
    at module.exports (/Users/rlz/projects/MenApp-cordova/plugins/cordova-plugin-firebase/scripts/after_prepare.js:139:5)
    at runScriptViaModuleLoader (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:188:18)
    at runScript (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:164:16)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:132:20
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:816:30)

**Comment by jafaripur** [comment]
Same for me!

**Comment by robertarnesson** [comment]
this is fixed in master. try to install the plugin directly from git master

**Comment by Birowsky** [comment]
@robertarnesson when do we expect a version?

**Comment by robertarnesson** [comment]
@Birowsky very soon - in a few days tops
