### ISSUE TITLE
Ionic cordova run android

### ISSUE THREAD

**Issue by victorhbv** [arnesson/cordova-plugin-firebase#606]
After update today for ionic build the following error appears:

 Command failed with exit code 1 Error output:
Exception in thread "main" java.lang.IllegalArgumentException
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:108)
	at com.google.devtools.build.android.desugar.DefaultMethodClassFixer$DefaultMethodFinder.visit(DefaultMethodClassFixer.java:471)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at com.google.devtools.build.android.desugar.DefaultMethodClassFixer.defaultMethodsDefined(DefaultMethodClassFixer.java:319)
	at com.google.devtools.build.android.desugar.DefaultMethodClassFixer.visitEnd(DefaultMethodClassFixer.java:88)
	at org.objectweb.asm.ClassVisitor.visitEnd(Unknown Source)
	at com.google.devtools.build.android.desugar.InterfaceDesugaring.visitEnd(InterfaceDesugaring.java:85)
	at org.objectweb.asm.ClassVisitor.visitEnd(Unknown Source)
	at com.google.devtools.build.android.desugar.LambdaDesugaring.visitEnd(LambdaDesugaring.java:150)
	at org.objectweb.asm.ClassVisitor.visitEnd(Unknown Source)
	at org.objectweb.asm.ClassVisitor.visitEnd(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at com.google.devtools.build.android.desugar.Desugar.desugarClassesInInput(Desugar.java:401)
	at com.google.devtools.build.android.desugar.Desugar.desugarOneInput(Desugar.java:326)
	at com.google.devtools.build.android.desugar.Desugar.desugar(Desugar.java:280)
	at com.google.devtools.build.android.desugar.Desugar.main(Desugar.java:584)

Exception in thread "main" java.lang.IllegalArgumentException
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:108)
	at com.google.devtools.build.android.desugar.DefaultMethodClassFixer$DefaultMethodFinder.visit(DefaultMethodClassFixer.java:471)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at com.google.devtools.build.android.desugar.DefaultMethodClassFixer.defaultMethodsDefined(DefaultMethodClassFixer.java:319)
	at com.google.devtools.build.android.desugar.DefaultMethodClassFixer.visitEnd(DefaultMethodClassFixer.java:88)
	at org.objectweb.asm.ClassVisitor.visitEnd(Unknown Source)
	at com.google.devtools.build.android.desugar.InterfaceDesugaring.visitEnd(InterfaceDesugaring.java:85)
	at org.objectweb.asm.ClassVisitor.visitEnd(Unknown Source)
	at com.google.devtools.build.android.desugar.LambdaDesugaring.visitEnd(LambdaDesugaring.java:150)
	at org.objectweb.asm.ClassVisitor.visitEnd(Unknown Source)
	at org.objectweb.asm.ClassVisitor.visitEnd(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at com.google.devtools.build.android.desugar.Desugar.desugarClassesInInput(Desugar.java:401)
	at com.google.devtools.build.android.desugar.Desugar.desugarOneInput(Desugar.java:326)
	at com.google.devtools.build.android.desugar.Desugar.desugar(Desugar.java:280)
	at com.google.devtools.build.android.desugar.Desugar.main(Desugar.java:584)

Exception in thread "main" java.lang.IllegalArgumentException
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:108)
	at com.google.devtools.build.android.desugar.DefaultMethodClassFixer$DefaultMethodFinder.visit(DefaultMethodClassFixer.java:471)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at com.google.devtools.build.android.desugar.DefaultMethodClassFixer.defaultMethodsDefined(DefaultMethodClassFixer.java:319)
	at com.google.devtools.build.android.desugar.DefaultMethodClassFixer.visitEnd(DefaultMethodClassFixer.java:88)
	at org.objectweb.asm.ClassVisitor.visitEnd(Unknown Source)
	at com.google.devtools.build.android.desugar.InterfaceDesugaring.visitEnd(InterfaceDesugaring.java:85)
	at org.objectweb.asm.ClassVisitor.visitEnd(Unknown Source)
	at com.google.devtools.build.android.desugar.LambdaDesugaring.visitEnd(LambdaDesugaring.java:150)
	at org.objectweb.asm.ClassVisitor.visitEnd(Unknown Source)
	at org.objectweb.asm.ClassVisitor.visitEnd(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at com.google.devtools.build.android.desugar.Desugar.desugarClassesInInput(Desugar.java:401)
	at com.google.devtools.build.android.desugar.Desugar.desugarOneInput(Desugar.java:326)
	at com.google.devtools.build.android.desugar.Desugar.desugar(Desugar.java:280)
	at com.google.devtools.build.android.desugar.Desugar.main(Desugar.java:584)

**Comment by zmazouzi** [comment]
have you got any updates I get the same error ... i'm using ionic 3.20.0 along with firebase

**Comment by manuel-dev** [comment]
Same problem here. Using Firebase and Admob with 3.20.0 installed this morning. Trying to revert to 3.19.1...

**Comment by DavidNrs** [comment]
Did you find any solution to this problem?

**Comment by victorhbv** [comment]
I updated the Android SDK, and also update all my projects dependences, and
it worked.

Atenciosamente,
Victor Hugo Braga Vieira
Cel.: (061) 8114-8773

**Comment by geekyguy18** [comment]
Same problem here, any fix for that?

**Comment by geekyguy18** [comment]
Here is the fix [https://github.com/arnesson/cordova-plugin-firebase/issues/612#issuecomment-376217404](url)

**Comment by soumak77** [comment]
this appears to be fixed by installing [cordova-android-play-services-gradle-release](https://github.com/dpa99c/cordova-android-play-services-gradle-release)

**Comment by MrDrProfX** [comment]
Same problem. None of the above fixes worked for me. More detail [here](https://forum.ionicframework.com/t/i-am-unable-to-build-for-android-due-to-desugar-error/129540)
Anyone have a fix for this desugar exception?

**Comment by hiepxanh** [comment]
`cordova clean
`
1 line fix bug

**Comment by erperejildo** [comment]
@geekyguy18  you need to do that every time you add the platform

@soumak77 I ran `cordova plugin add cordova-android-play-services-gradle-release` and tried to build and didn't work

**Comment by hiepxanh** [comment]
it's `clean `not `clear`

**Comment by erperejildo** [comment]
sorry, but yes, I was using `clean`

**Comment by onesimusaz** [comment]
`cordova clean` 
worked for me too, but I wish some of these fixes didn't feel so much like magic.

**Comment by erperejildo** [comment]
I also tried creating a new project and moving just my app files and trying again.

Nothing
