### ISSUE TITLE
problem installing plugin 

### ISSUE THREAD

**Issue by juanpablogd** [arnesson/cordova-plugin-firebase#694]
Hello

"cordova plugin add cordova-plugin-firebase --save" doesn't work in android 7.0.0

![image](https://user-images.githubusercontent.com/2925728/40068033-3fd54252-582d-11e8-97cd-cd831301452b.png)

nothing happened

thanks in advance

**Comment by Hlaphoneo** [comment]
What was the installation output ? , please give us more information.

**Comment by geobotsar** [comment]
Hi, facing issues when i try to install the plugin on cordova with android platform, here is the output:

Preparing Firebase on Android
TypeError: Cannot read property 'current_key' of undefined
    at updateStringsXml (C:\Users\geobotsar\projects\phonegap\public\homebrewshopsapp\plugins\cordova-plugin-firebase\scripts\after_prepare.js:72:160)
    at copyKey (C:\Users\geobotsar\projects\phonegap\public\homebrewshopsapp\plugins\cordova-plugin-firebase\scripts\after_prepare.js:94:29)
    at module.exports (C:\Users\geobotsar\projects\phonegap\public\homebrewshopsapp\plugins\cordova-plugin-firebase\scripts\after_prepare.js:139:9)
    at runScriptViaModuleLoader (C:\Users\geobotsar\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\hooks\HooksRunner.js:188:18)
    at runScript (C:\Users\geobotsar\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\hooks\HooksRunner.js:164:16)
    at C:\Users\geobotsar\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\hooks\HooksRunner.js:132:20
    at _fulfilled (C:\Users\geobotsar\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:787:54)
    at self.promiseDispatch.done (C:\Users\geobotsar\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:816:30)
    at Promise.promise.promiseDispatch (C:\Users\geobotsar\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:749:13)
    at C:\Users\geobotsar\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:509:49
    at flush (C:\Users\geobotsar\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
--save flag or autosave detected
Saving android@~7.0.0 into config.xml file ...
