### ISSUE TITLE
Failing to build on PGB - Plugin with id 'com.google.gms.google-services' not found.

### ISSUE THREAD

**Issue by slackernrrd** [arnesson/cordova-plugin-firebase#907]
I am trying to build my app on PhoneGap Build and have forked this plugin (v2.0.4) as the instructions say (I have however not edited the config files, instead I opted to remove them in my version of the plugin, and then used `<resource-file>` in my config.xml to copy them to the correct location). This seems to work fine for iOS - yay! But my Android version is refusing to build.

I am getting the following error:
```
BUILD FAILED in 6s
Error: /gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* Where:
Script '/cordova-plugin-firebase/app-build.gradle' line: 27

* What went wrong:
A problem occurred evaluating project ':app'.
> Plugin with id 'com.google.gms.google-services' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
    at ChildProcess.whenDone (/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

I have looked at other issues where people got the same error, but all of them are closed and none of them(?) seem to be about PhoneGap Build.

As I understand it the build hook scripts add something to the project level gradle file, but hooks don't run on PhoneGap Build. Is it at all possible to build this plugin on PGB for Android at the moment?

It seems this error can also show up if you have plugins with conflicting dependencies on Google Play Services, but as far as I know no other plugins i use have a dependency on it.

```
    <plugin name="cordova-plugin-datepicker" source="npm" spec="^0.9.3" />
    <plugin name="cordova-plugin-dialogs" source="npm" spec="~1.3.3" />
    <plugin name="cordova-plugin-file" source="npm" spec="~4.3.3" />
    <plugin name="cordova-plugin-globalization" source="npm" spec="~1.0.7" />
    <plugin name="cordova-plugin-inappbrowser" source="npm" spec="~1.7.1" />
    <plugin name="cordova-plugin-network-information" source="npm" spec="~1.3.3" />
    <plugin name="cordova-plugin-whitelist" spec="^1.3.3" />
    <plugin name="cordova-plugin-firebase" source="git" spec="https://bitbucket.org/xxx/custom-firebase.git#xxxxxxx" />
```

I have tried adding `<plugin name="cordova-support-google-services" spec="^1.2.1" />` as well as `<plugin name="cordova-android-play-services-gradle-release" />` and `<plugin name="cordova-android-firebase-gradle-release" />` in different combinations but nothing will work.

Does anyone have a solution? Does anyone have v2.0.4 working with PGB, so I at least know if it's worth even trying to find a solution?

**Comment by briantq** [comment]
@slackernrrd I don't have any experience with PhoneGap.  The issue is that you are missing the plugin and repository modifications in the root build.gradle from the [Firebase Android Install Guide](https://firebase.google.com/docs/android/setup).

I see two options.  1.  See what you can do to get the install hooks working so they can modify the build.gradle so you don't have two.  2. Find some other way to modify the build.gradle to add the required lines.  Please note there are two build.gradles, one at the root and another in the app directory.  You need to modify the one in the root.

**Comment by slackernrrd** [comment]
@briantq Phonegap Build is a popular cloud build service from Adobe that enables developers to build for devices without having all the different development environments (so you don't need a Mac to build for iOS, for example).

My issue _is_ with the hooks not running (because of a limitation with Phonegap Build), thus not modifying the root build.gradle. Phonegap Build automates and abstracts away some details, which means there is no way for me to edit that file.

The README of this plugin suggests that there is a way to get it to work with PGB. My question is - is this not true? If so, maybe that section of the README should be updated. But if the plugin indeed does work with PGB, which I hope, is there any solution to my problem?

**Comment by briantq** [comment]
@slackernrrd I was unaware of the README entry.  You are right, that does suggest that.  I don't believe that will work any more based with the updates to Firebase integration guides.  

If PGB doesn't run any hooks, how do you configure plugins?  In theory you will need to modify the build.gradle copy some Google config files, and maybe something else.  Do you do those steps manually and check in the result or do is that something you can work into your own build script?  I would have to think PGB would need to have some best practices on how to account for configuring plugins.

@soumak77 we might need to remove or at least update the directions with PGB.

**Comment by soumak77** [comment]
We can update the PGB section to reference the Firebase docs as to what needs to be added to the gradle files. We should also mention what needs to be manually done for the iOS build.

**Comment by slackernrrd** [comment]
> If PGB doesn't run any hooks, how do you configure plugins?

I have been using PGB for years, and most (not all) plugins just work. I have never had a similar issue before.

> In theory you will need to modify the build.gradle copy some Google config files, and maybe something else. Do you do those steps manually and check in the result or do is that something you can work into your own build script? I would have to think PGB would need to have some best practices on how to account for configuring plugins.

Most (hmm probably all) configuration is done in config.xml. All plugins defined in config.xml are downloaded by PGB. The only thing you need to upload is config.xml and the www folder (you _can_ upload other things too, like resources, but _not_ the platforms folder, that gets built for you and is pretty much the point of PGB). You can set variables for a plugin, you may use `<config-file>` and use other mechanisms in config.xml.

This may sound limiting, but like I said, it hasn't really felt like a big problem (but then again I guess I've avoided plugins that say they _don't_ support PGB).

I should mention that I did manage to get rid of the error in my original post, but the Android version still won't build. By replacing

```
cdvPluginPostBuildExtras.add({
    apply plugin: 'com.google.gms.google-services'
    apply plugin: 'io.fabric'
})
```

with

```
cdvPluginPostBuildExtras.add({
    apply plugin: 'com.google.gms.googleservices.GoogleServicesPlugin'
    apply plugin: 'com.crashlytics.tools.gradle.CrashlyticsPlugin'
})
```

it doesn't complain that the plugin is not found, instead i get

```
FAILURE: Build failed with an exception.

* What went wrong:
no management in java.library.path
```

which was a dead end for me.

**Comment by briantq** [comment]
@slackernrrd The reason that did not work is that the plugin (or really where the plugin needs to resolve from) needs to be in the root build.gradle file.  Android has two build.gradles (it is a bit confusing).  The build.gradle under the app directory is used to build the project.  Google created a plugin that needs to run as part of the app build, so it needs to be able to resolve itself when the app build.gradle starts (hence the references in the root build.gradle).

Based on the fact that Firebase requires you to modify your root build.gradle to resolve the plugins to actually build the project, I am not sure how you can do that without hooks during the build.  This limitation is really due to Firebase requiring those file modifications to build properly.

The totally nutty thought would be to run the build to install the cordova plugins, wait for the build to fail, modify the files yourself with a script, then run the build again...  That seems like a crazy hack.  Additionally, you are going to have problems with the GoogleServices files that need to be copied over with your account information.  

One thought might be to stick on 1.0.5 as that should work still, though I don't like that suggestion either.

**Comment by augustomurri** [comment]
Same problem here
`BUILD FAILED in 1s
cmd: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\.......\platforms\android\cordova-support-google-services\app-build.gradle' line: 16

* What went wrong:
A problem occurred evaluating project ':app'.
> Failed to apply plugin [class 'com.google.gms.googleservices.GoogleServicesPlugin']
   > For input string: "+"`

`    <plugin name="cordova-plugin-splashscreen" spec="^5.0.2" />
    <plugin name="onesignal-cordova-plugin" spec="~2.4.3" />
    <plugin name="cordova-plugin-whitelist" spec="^1.3.3" />
    <plugin name="cordova-plugin-firebase" spec="^2.0.5" />
    <plugin name="cordova-plugin-network-information" spec="^2.0.1" />
    <plugin name="phonegap-plugin-push" spec="^2.2.3">
        <variable name="ANDROID_SUPPORT_V13_VERSION" value="27.+" />
        <variable name="FCM_VERSION" value="11.6.2" />
    </plugin>`

**Comment by thienanle** [comment]
@slackernrrd did you end up finding a solution to this? I'm having the same issue.

**Comment by thienanle** [comment]
I'm on v2.0.5 of cordova-plugin-firebase.

```
* What went wrong:
A problem occurred evaluating project ':app'.
> Plugin with id 'com.google.gms.google-services' not found.
```

Because PGB doesn't support hooks, I think the problem here is that the `after_plugin_install` hook never runs, so build.gradle is never updated to include the `com.google.gms.google-services` dependency.

**Comment by slackernrrd** [comment]
@thienanle Unfortunately I didn't find a solution. I ended up abandoning Firebase in favor of Google Analytics since right now I only need the analytics part. But I would like to find a solution for the future.

**Comment by aramgev** [comment]
I am also have the same problem with building this plugin with PGB. Did you find any solution?

**Comment by Aggror** [comment]
With the announced deprecation of the official push plugin (which supports phonegap build), more and more users will want to switch to this firebase plugin. I would also be very interested in seeing support for this. 
As mentioned above, the hook issue could be evaded by placing the .plist and google-services.json in the root of the project and let the config.xml reference and copy them to the correct folder.
```
  <platform name="android" >
    <resource-file src="google-services.json" target="app/google-services.json" />
  </platform>
  <platform name="ios">
    <resource-file src="GoogleService-Info.plist" target="app/GoogleService-Info.plist" />
  </platform>
  <engine name="android" spec="6.4.0" />
  <plugin name="cordova-plugin-firebase"                 spec="2.0.0"/>
```
Unfortunately the reported error during the build keeps popping up.
`A problem occurred evaluating project ':app'.
> Plugin with id 'com.google.gms.google-services' not found.`

**Comment by briantq** [comment]
@Aggror the hooks don't just move the plist and json, they also make the required modifications to the build.gradle, that allow the google service plugin to run during the build process.  Without running this plugin, Firebase won't install correctly.  Firebase _requires_ this to be run and hence the build.gradle to be modified.  Hooks are the only way to make this modification automatically.  

The only work around I can think of is to start checking in the Android project files after you modify them.

I would be happy to hear any suggestions you have as right now sinceFB requiring both build.gradles to be modified, Cordova not supporting root build.gradle files to be modified via config.xml, and PGB not supporting hooks, I really don't see how anyone using PGB can use FB at all, in this plugin or any other.

**Comment by Aggror** [comment]
@briantq Thanks for the reply.
I have working firebase push messages using the [phonegap push plugin](https://github.com/phonegap/phonegap-plugin-push) and PG build, so it possible somehow.  I will keep looking for an answer, but so far I am in the dark.

**Comment by gihangt** [comment]
@briantq I was having the same problem with PhoneGap build. It is working now after replacing  "cdvPluginPostBuildExtras. add ({ ... "
with this 
"apply plugin: com.google.gms.googleservices.GoogleServicesPlugin"

**Comment by aramgev** [comment]
@gihangt thanks for reply,
I did what you suggest, and was able to build app. But know when I open application it crashes, with these error: 

```
11-29 13:09:52.965 24222 24339 E AndroidRuntime: java.lang.IllegalStateException: Must Initialize Fabric before using singleton()
11-29 13:09:52.965 24222 24339 E AndroidRuntime:        at io.fabric.sdk.android.Fabric.singleton(Fabric.java:275)
11-29 13:09:52.965 24222 24339 E AndroidRuntime:        at io.fabric.sdk.android.Fabric.getKit(Fabric.java:525)
11-29 13:09:52.965 24222 24339 E AndroidRuntime:        at com.crashlytics.android.Crashlytics.getInstance(Crashlytics.java:188)
11-29 13:09:52.965 24222 24339 E AndroidRuntime:        at com.crashlytics.android.Crashlytics.checkInitialized(Crashlytics.java:371)
11-29 13:09:52.965 24222 24339 E AndroidRuntime:        at com.crashlytics.android.Crashlytics.logException(Crashlytics.java:207)
11-29 13:09:52.965 24222 24339 E AndroidRuntime:        at org.apache.cordova.firebase.FirebasePlugin$25.run(FirebasePlugin.java:824)
11-29 13:09:52.965 24222 24339 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
11-29 13:09:52.965 24222 24339 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
```

**Comment by gihangt** [comment]
@aramgev I can’t see these two lines on your build.gradle.
apply plugin: com.google .....
apply plugin: com.crash......

**Comment by aramgev** [comment]
@gihangt  Thanks, I add these lines, but it doesn't help. Application again crashes, and I get the exception above

**Comment by linghenrik** [comment]
Having the same issue on PGB and would love to get an update here. Is this a confirmed bug and will be handled ? Has anybody gotten v2.0.5 working on PGB ?

**Comment by daksamedia** [comment]
Hello all,

I'm new on this plugin, could explain even more for newbie like me
how to use it on the Phonegap Build projects?

Thanks in advance
