### ISSUE TITLE
Build fails on Android and Phonegap Build

### ISSUE THREAD

**Issue by WGMB** [arnesson/cordova-plugin-firebase#946]
When trying to build the latest version v2.0.5 of the plugin with Phonegap Build, the Android build fails and producing the following error:

```
FAILURE: Build failed with an exception.

* Where:
Script '/cordova-plugin-firebase/firebase-build.gradle' line: 27

* What went wrong:
A problem occurred evaluating project ':app'.
> Plugin with id 'com.google.gms.google-services' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
Error: /gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* Where:
Script '/cordova-plugin-firebase/firebase-build.gradle' line: 27

* What went wrong:
A problem occurred evaluating project ':app'.
> Plugin with id 'com.google.gms.google-services' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
    at ChildProcess.whenDone (/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

**To Reproduce**
Just build with PGB the v2.0.5 of the plugin, the Android build will fail.

**Expected behavior**
The plugin should be able to build with PGB like it used to do on v1.0.5

**Plugin Version**
v2.0.5

**Comment by yeahstyle** [comment]
I tried v1.0.5 and it doesn't work either

```
Ld /Users/alvarolaptop/Library/Developer/Xcode/DerivedData/OLBG-gumtqyxkhsixxqecnpedtvgelejp/Build/Intermediates.noindex/ArchiveIntermediates/OLBG/IntermediateBuildFilesPath/OLBG.build/Release-iphoneos/OLBG.build/Objects-normal/armv7/OLBG normal armv7 (in target: OLBG)
    cd /Users/alvarolaptop/Dropbox/OLBG/products/web-app/olbg-web-app/olbg-hybrid-app/platforms/ios
    export IPHONEOS_DEPLOYMENT_TARGET=9.0
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch armv7 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk -L/Users/alvarolaptop/Library/Developer/Xcode/DerivedData/OLBG-gumtqyxkhsixxqecnpedtvgelejp/Build/Intermediates.noindex/ArchiveIntermediates/OLBG/BuildProductsPath/Release-iphoneos -L/Users/alvarolaptop/Library/Developer/Xcode/DerivedData/OLBG-gumtqyxkhsixxqecnpedtvgelejp/Build/Intermediates.noindex/ArchiveIntermediates/OLBG/BuildProductsPath/Release-iphoneos/GoogleToolboxForMac -L/Users/alvarolaptop/Library/Developer/Xcode/DerivedData/OLBG-gumtqyxkhsixxqecnpedtvgelejp/Build/Intermediates.noindex/ArchiveIntermediates/OLBG/BuildProductsPath/Release-iphoneos/Protobuf -L/Users/alvarolaptop/Library/Developer/Xcode/DerivedData/OLBG-gumtqyxkhsixxqecnpedtvgelejp/Build/Intermediates.noindex/ArchiveIntermediates/OLBG/BuildProductsPath/Release-iphoneos/nanopb -L/Users/alvarolaptop/Library/Developer/Xcode/DerivedData/OLBG-gumtqyxkhsixxqecnpedtvgelejp/Build/Intermediates.noindex/ArchiveIntermediates/OLBG/BuildProductsPath/Release-iphoneos/GoogleToolboxForMac -L/Users/alvarolaptop/Library/Developer/Xcode/DerivedData/OLBG-gumtqyxkhsixxqecnpedtvgelejp/Build/Intermediates.noindex/ArchiveIntermediates/OLBG/BuildProductsPath/Release-iphoneos/Protobuf -L/Users/alvarolaptop/Library/Developer/Xcode/DerivedData/OLBG-gumtqyxkhsixxqecnpedtvgelejp/Build/Intermediates.noindex/ArchiveIntermediates/OLBG/BuildProductsPath/Release-iphoneos/nanopb -L/Users/alvarolaptop/Dropbox/OLBG/products/web-app/olbg-web-app/olbg-hybrid-app/platforms/ios/OLBG/Plugins/cordova-plugin-appsflyer-sdk -L/Users/alvarolaptop/Dropbox/OLBG/products/web-app/olbg-web-app/olbg-hybrid-app/platforms/ios/OLBG/Plugins/cordova-plugin-google-app-conversion-tracker -F/Users/alvarolaptop/Library/Developer/Xcode/DerivedData/OLBG-gumtqyxkhsixxqecnpedtvgelejp/Build/Intermediates.noindex/ArchiveIntermediates/OLBG/BuildProductsPath/Release-iphoneos -F/Users/alvarolaptop/Dropbox/OLBG/products/web-app/olbg-web-app/olbg-hybrid-app/platforms/ios/Pods/FirebaseAnalytics/Frameworks -F/Users/alvarolaptop/Dropbox/OLBG/products/web-app/olbg-web-app/olbg-hybrid-app/platforms/ios/Pods/FirebaseCore/Frameworks -F/Users/alvarolaptop/Dropbox/OLBG/products/web-app/olbg-web-app/olbg-hybrid-app/platforms/ios/Pods/FirebaseInstanceID/Frameworks -F/Users/alvarolaptop/Dropbox/OLBG/products/web-app/olbg-web-app/olbg-hybrid-app/platforms/ios/Pods/FirebaseMessaging/Frameworks -F/Users/alvarolaptop/Dropbox/OLBG/products/web-app/olbg-web-app/olbg-hybrid-app/platforms/ios/Pods/FirebaseAnalytics/Frameworks -F/Users/alvarolaptop/Dropbox/OLBG/products/web-app/olbg-web-app/olbg-hybrid-app/platforms/ios/Pods/FirebaseCore/Frameworks -F/Users/alvarolaptop/Dropbox/OLBG/products/web-app/olbg-web-app/olbg-hybrid-app/platforms/ios/Pods/FirebaseInstanceID/Frameworks -F/Users/alvarolaptop/Dropbox/OLBG/products/web-app/olbg-web-app/olbg-hybrid-app/platforms/ios/Pods/FirebaseMessaging/Frameworks -FOLBG/Plugins/cordova-plugin-firebase -FOLBG/Plugins/cordova-plugin-firebase -FOLBG/Plugins/cordova-plugin-firebase -FOLBG/Plugins/cordova-plugin-firebase -FOLBG/Plugins/cordova-plugin-firebase -FOLBG/Plugins/cordova-plugin-firebase -FOLBG/Plugins/cordova-plugin-firebase -FOLBG/Plugins/cordova-plugin-firebase -FOLBG/Plugins/cordova-plugin-firebase -FOLBG/Plugins/cordova-plugin-firebase -FOLBG/Plugins/cordova-plugin-firebase -FOLBG/Plugins/cordova-plugin-firebase -FOLBG/Plugins/cordova-plugin-firebase -FOLBG/Plugins/cordova-plugin-firebase -FOLBG/Plugins/cordova-plugin-firebase -FOLBG/Plugins/cordova-plugin-firebase -FOLBG/Plugins/cordova-plugin-firebase -FOLBG/Plugins/cordova-plugin-firebase -FOLBG/Plugins/cordova-plugin-firebase -FOLBG/Plugins/cordova-plugin-firebase -FOLBG/Plugins/cordova-plugin-firebase -FOLBG/Plugins/cordova-plugin-firebase -FOLBG/Plugins/cordova-plugin-firebase -FOLBG/Plugins/cordova-plugin-firebase -FOLBG/Plugins/cordova-plugin-firebase -FOLBG/Plugins/cordova-plugin-firebase -FOLBG/Plugins/cordova-plugin-firebase -FOLBG/Plugins/cordova-plugin-firebase -FOLBG/Plugins/cordova-plugin-firebase -FOLBG/Plugins/cordova-plugin-firebase -FOLBG/Plugins/cordova-plugin-firebase -FOLBG/Plugins/cordova-plugin-firebase -FOLBG/Plugins/cordova-plugin-firebase -FOLBG/Plugins/cordova-plugin-firebase -FOLBG/Plugins/cordova-plugin-firebase -FOLBG/Plugins/cordova-plugin-firebase -FOLBG/Plugins/cordova-plugin-firebase -FOLBG/Plugins/cordova-plugin-firebase -FOLBG/Plugins/cordova-plugin-firebase -FOLBG/Plugins/cordova-plugin-firebase -FOLBG/Plugins/cordova-plugin-firebase -FOLBG/Plugins/cordova-plugin-firebase -FOLBG/Plugins/cordova-plugin-firebase -FOLBG/Plugins/cordova-plugin-firebase -FOLBG/Plugins/cordova-plugin-firebase -FOLBG/Plugins/cordova-plugin-firebase -FOLBG/Plugins/cordova-plugin-firebase -FOLBG/Plugins/cordova-plugin-firebase -FOLBG/Plugins/cordova-plugin-firebase -FOLBG/Plugins/cordova-plugin-firebase -FOLBG/Plugins/cordova-plugin-firebase -FOLBG/Plugins/cordova-plugin-firebase -FOLBG/Plugins/cordova-plugin-firebase -FOLBG/Plugins/cordova-plugin-firebase -FOLBG/Plugins/cordova-plugin-firebase -FOLBG/Plugins/cordova-plugin-firebase -FOLBG/Plugins/cordova-plugin-firebase -FOLBG/Plugins/cordova-plugin-firebase -FOLBG/Plugins/cordova-plugin-firebase -FOLBG/Plugins/cordova-plugin-firebase -FOLBG/Plugins/cordova-plugin-firebase -FOLBG/Plugins/cordova-plugin-firebase -FOLBG/Plugins/cordova-plugin-firebase -FOLBG/Plugins/cordova-plugin-firebase -FOLBG/Plugins/cordova-plugin-firebase -FOLBG/Plugins/cordova-plugin-firebase -FOLBG/Plugins/cordova-plugin-firebase -FOLBG/Plugins/cordova-plugin-firebase -FOLBG/Plugins/cordova-plugin-firebase -FOLBG/Plugins/cordova-plugin-firebase -FOLBG/Plugins/cordova-plugin-firebase -FOLBG/Plugins/cordova-plugin-firebase -filelist /Users/alvarolaptop/Library/Developer/Xcode/DerivedData/OLBG-gumtqyxkhsixxqecnpedtvgelejp/Build/Intermediates.noindex/ArchiveIntermediates/OLBG/IntermediateBuildFilesPath/OLBG.build/Release-iphoneos/OLBG.build/Objects-normal/armv7/OLBG.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -miphoneos-version-min=9.0 -dead_strip -Xlinker -object_path_lto -Xlinker /Users/alvarolaptop/Library/Developer/Xcode/DerivedData/OLBG-gumtqyxkhsixxqecnpedtvgelejp/Build/Intermediates.noindex/ArchiveIntermediates/OLBG/IntermediateBuildFilesPath/OLBG.build/Release-iphoneos/OLBG.build/Objects-normal/armv7/OLBG_lto.o -Xlinker -final_output -Xlinker /Applications/OLBG.app/OLBG -fobjc-arc -fobjc-link-runtime -ObjC -ObjC -lGoogleToolboxForMac -lProtobuf -lc++ -lnanopb -lsqlite3 -lz -framework AddressBook -framework FirebaseAnalytics -framework FirebaseCore -framework FirebaseCoreDiagnostics -framework FirebaseInstanceID -framework FirebaseMessaging -framework FirebaseNanoPB -framework StoreKit -framework SystemConfiguration -ObjC -lGoogleToolboxForMac -lProtobuf -lc++ -lnanopb -lsqlite3 -lz -framework AddressBook -framework FirebaseAnalytics -framework FirebaseCore -framework FirebaseCoreDiagnostics -framework FirebaseInstanceID -framework FirebaseMessaging -framework FirebaseNanoPB -framework StoreKit -framework SystemConfiguration /Users/alvarolaptop/Library/Developer/Xcode/DerivedData/OLBG-gumtqyxkhsixxqecnpedtvgelejp/Build/Intermediates.noindex/ArchiveIntermediates/OLBG/BuildProductsPath/Release-iphoneos/libCordova.a -framework SystemConfiguration -lz -framework StoreKit -weak_framework AdSupport -lAppsFlyerLib -weak_framework iAd -weak_framework Security -weak_framework AudioToolbox -framework CoreLocation -lGoogleConversionTracking -framework CoreSpotlight -framework CoreTelephony -weak_framework Social -weak_framework MessageUI -lPods-OLBG -framework FirebaseAnalytics -framework FirebaseCore -framework FirebaseCoreDiagnostics -framework FirebaseInstanceID -framework FirebaseNanoPB -framework GoogleToolboxForMac -framework nanopb -framework Protobuf -framework FirebaseMessaging -framework Fabric -framework Crashlytics -framework FirebaseRemoteConfig -framework FirebaseABTesting -framework FirebaseAuth -framework GTMSessionFetcher -framework FirebasePerformance -framework FirebaseISASwizzler -framework FirebaseMethodSwizzler -Xlinker -dependency_info -Xlinker /Users/alvarolaptop/Library/Developer/Xcode/DerivedData/OLBG-gumtqyxkhsixxqecnpedtvgelejp/Build/Intermediates.noindex/ArchiveIntermediates/OLBG/IntermediateBuildFilesPath/OLBG.build/Release-iphoneos/OLBG.build/Objects-normal/armv7/OLBG_dependency_info.dat -o /Users/alvarolaptop/Library/Developer/Xcode/DerivedData/OLBG-gumtqyxkhsixxqecnpedtvgelejp/Build/Intermediates.noindex/ArchiveIntermediates/OLBG/IntermediateBuildFilesPath/OLBG.build/Release-iphoneos/OLBG.build/Objects-normal/armv7/OLBG

Undefined symbols for architecture armv7:
  "_kFIRLoggerSwizzler", referenced from:
      ___63+[FIRSwizzler swizzleClass:selector:isClassSelector:withBlock:]_block_invoke in FirebaseMethodSwizzler(FIRSwizzler_82e11d7d79f6bfec451c7947188678ce.o)
  "_FIRAuthStateDidChangeInternalNotificationUIDKey", referenced from:
      -[FIRAuth possiblyPostAuthStateChangeNotification] in FirebaseAuth(FIRAuth_2366ac320b953f0bc7fcfa8add28b99c.o)
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
any idea of what might be going on?

**Comment by WGMB** [comment]
I've managed to make it build with PGB.
The build.gradle file has to be modified like this: https://github.com/gihangt/cordova-plugin-firebase/commit/2691fac41c13c7159c262d009a3eae5b76cd15c8

Also the google-services.json file has to be added on the project root and be copied using the resource-file tag via config.xml:


<resource-file src="google-services.json" target="app/google-services.json" />

The iOS resource (GoogleService-Info.plist) will be copied via the plugin.xml configuration:

<resource-file src="src/ios/GoogleService-Info.plist" />

**Comment by edvenkat** [comment]
@WGMB 
```
<platform name="android">
      <resource-file src="google-services.json" target="." />
</platform>
```

i try to add the google-services.json from config like above but getting error "Google services.json" is missing

can you please advice on this

**Comment by jeffreyvr** [comment]
@edvenkat Did you end up getting it to work?
